name: NetworkCore
version: '1.0-SNAPSHOT'
main: me.cosmic.networkcore.NetworkCore
authors: [ etuu ]
commands:
  friend:
    aliases:
      - f
  executequery:
    description: executes a query on the networkcore database